services:
  rainbow-gen:
    build: .
    container_name: rainbow_generator
    deploy:
      resources:
        limits:
          cpus: '72'          
          memory: 200G        
    
    volumes:
      - rainbow_data:/app
      - /mnt/stockage/rainbow_project/tables:/app/tables
    
    tmpfs:
      - /app/tmp:size=100G,mode=1777
    
    environment:
      - TERM=xterm-256color      
    
    stdin_open: true
    tty: true
    
volumes:
  rainbow_data: